name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Recommended for Django 5.x

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install Dependencies
      run: pipenv sync --dev

    - name: Check for Missing Migrations
      run: |
        pipenv run python manage.py makemigrations --check --dry-run
      # This ensures you didn't forget to commit migration files

    - name: Run Tests
      run: |
        pipenv run python manage.py test report
