name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Recommended for Django 5.x

    - name: Install Pipenv
      run: pip install pipenv

  - name: Install Dependencies
        run: |
          pip install pipenv
          # --deploy ensures the Pipfile.lock is up to date
          # --dev includes testing tools like coverage or pytest
          pipenv install --dev --deploy 
  
      - name: Check for Missing Migrations
        run: |
          pipenv run python manage.py makemigrations --check --dry-run
  
      - name: Run Tests
        run: |
          pipenv run python manage.py test report
